insert into public.prompts (id,slug,title,category,tags,description,variables,tier,char_count) values
('pmm-positioning-teardown','pmm-positioning-teardown',$hs$Positioning teardown$hs$,$hs$PMM/GTM$hs$,ARRAY[$hs$positioning$hs$,$hs$competitive$hs$,$hs$messaging$hs$]::text[],$hs$Pressure-test a positioning statement against alternatives and the real competitive set.$hs$,ARRAY[$hs$POSITIONING STATEMENT$hs$,$hs$CATEGORY$hs$,$hs$COMPETITORS$hs$,$hs$ICP$hs$]::text[],'public',871),
('pmm-launch-narrative','pmm-launch-narrative',$hs$Launch narrative builder$hs$,$hs$PMM/GTM$hs$,ARRAY[$hs$launch$hs$,$hs$narrative$hs$,$hs$messaging$hs$]::text[],$hs$Turn a feature list into a "why now" story leadership and press will repeat.$hs$,ARRAY[$hs$PRODUCT/FEATURE$hs$,$hs$AUDIENCE$hs$,$hs$LIST$hs$,$hs$SHIFT$hs$]::text[],'public',745),
('pmm-messaging-house','pmm-messaging-house',$hs$Messaging house$hs$,$hs$PMM/GTM$hs$,ARRAY[$hs$messaging$hs$,$hs$positioning$hs$,$hs$framework$hs$]::text[],$hs$Build a one-page messaging hierarchy the whole org can repeat consistently.$hs$,ARRAY[$hs$PRODUCT$hs$,$hs$BUYER$hs$,$hs$JOBS$hs$,$hs$DIFFERENTIATORS$hs$]::text[],'public',567),
('pmm-competitive-battlecard','pmm-competitive-battlecard',$hs$Competitive battlecard$hs$,$hs$PMM/GTM$hs$,ARRAY[$hs$competitive$hs$,$hs$sales$hs$,$hs$enablement$hs$]::text[],$hs$Arm sales to win against a specific competitor without trashing them.$hs$,ARRAY[$hs$COMPETITOR$hs$,$hs$STRENGTHS$hs$,$hs$WEAKNESSES$hs$,$hs$THEIR REP$hs$]::text[],'public',513),
('pmm-icp-definition','pmm-icp-definition',$hs$ICP sharpener$hs$,$hs$PMM/GTM$hs$,ARRAY[$hs$icp$hs$,$hs$segmentation$hs$,$hs$strategy$hs$]::text[],$hs$Replace a vague "everyone" ICP with the segment that actually converts.$hs$,ARRAY[$hs$CURRENT ICP$hs$,$hs$WON TRAITS$hs$,$hs$CHURN TRAITS$hs$]::text[],'public',533),
('pmm-launch-tiering','pmm-launch-tiering',$hs$Launch tiering + GTM plan$hs$,$hs$PMM/GTM$hs$,ARRAY[$hs$launch$hs$,$hs$gtm$hs$,$hs$planning$hs$]::text[],$hs$Right-size a launch so effort matches business impact.$hs$,ARRAY[$hs$FEATURE/PRODUCT$hs$,$hs$DATE$hs$,$hs$WHY IT MATTERS$hs$,$hs$SIZE/SEGMENT$hs$]::text[],'public',558),
('pmm-pricing-narrative','pmm-pricing-narrative',$hs$Pricing & packaging narrative$hs$,$hs$PMM/GTM$hs$,ARRAY[$hs$pricing$hs$,$hs$packaging$hs$,$hs$strategy$hs$]::text[],$hs$Explain a pricing change so customers feel value, not extraction.$hs$,ARRAY[$hs$PRODUCT$hs$,$hs$CURRENT$hs$,$hs$NEW$hs$,$hs$REASON$hs$]::text[],'public',608),
('pmm-analyst-briefing','pmm-analyst-briefing',$hs$Analyst briefing prep$hs$,$hs$PMM/GTM$hs$,ARRAY[$hs$analyst-relations$hs$,$hs$narrative$hs$,$hs$enablement$hs$]::text[],$hs$Prep a tight, evidence-backed story for an analyst (Gartner/Forrester) briefing.$hs$,ARRAY[$hs$ANALYST/FIRM$hs$,$hs$MARKET$hs$,$hs$NEWS$hs$,$hs$DIFF$hs$]::text[],'public',490),
('pmm-customer-story','pmm-customer-story',$hs$Customer story extractor$hs$,$hs$PMM/GTM$hs$,ARRAY[$hs$case-study$hs$,$hs$content$hs$,$hs$proof$hs$]::text[],$hs$Turn a raw customer interview into a structured, metric-led case study.$hs$,ARRAY[$hs$NOTES$hs$,$hs$METRICS$hs$]::text[],'public',489),
('pmm-sales-enablement-onepager','pmm-sales-enablement-onepager',$hs$Sales one-pager$hs$,$hs$PMM/GTM$hs$,ARRAY[$hs$enablement$hs$,$hs$sales$hs$,$hs$content$hs$]::text[],$hs$A leave-behind reps actually use in a deal.$hs$,ARRAY[$hs$PRODUCT$hs$,$hs$BUYER PERSONA$hs$,$hs$DEAL STAGE$hs$,$hs$CONCERN$hs$]::text[],'public',401),
('pmm-win-loss','pmm-win-loss',$hs$Win/loss synthesis$hs$,$hs$PMM/GTM$hs$,ARRAY[$hs$research$hs$,$hs$competitive$hs$,$hs$strategy$hs$]::text[],$hs$Find the pattern across deals you won and lost, with an action list.$hs$,ARRAY[$hs$DEAL NOTES$hs$]::text[],'public',455),
('pmm-landing-page','pmm-landing-page',$hs$Landing page copy$hs$,$hs$PMM/GTM$hs$,ARRAY[$hs$copy$hs$,$hs$conversion$hs$,$hs$content$hs$]::text[],$hs$High-converting page copy structured around one action.$hs$,ARRAY[$hs$PRODUCT$hs$,$hs$GOAL$hs$,$hs$AUDIENCE$hs$]::text[],'public',530),
('pmm-gtm-readiness','pmm-gtm-readiness',$hs$GTM readiness checklist$hs$,$hs$PMM/GTM$hs$,ARRAY[$hs$launch$hs$,$hs$operations$hs$,$hs$planning$hs$]::text[],$hs$A go/no-go review that surfaces the gaps before launch day.$hs$,ARRAY[$hs$LAUNCH$hs$,$hs$DATE$hs$]::text[],'public',470),
('pmm-naming','pmm-naming',$hs$Product / feature naming$hs$,$hs$PMM/GTM$hs$,ARRAY[$hs$naming$hs$,$hs$branding$hs$,$hs$positioning$hs$]::text[],$hs$Generate and stress-test names against strategy, not just taste.$hs$,ARRAY[$hs$PRODUCT/FEATURE$hs$,$hs$FUNCTION$hs$,$hs$VOICE$hs$,$hs$CONSTRAINTS$hs$]::text[],'public',502),
('exec-board-update','exec-board-update',$hs$Board update tightener$hs$,$hs$Executive$hs$,ARRAY[$hs$board$hs$,$hs$comms$hs$,$hs$strategy$hs$]::text[],$hs$Compress a messy update into a board-ready narrative with the ask up front.$hs$,ARRAY[$hs$NOTES$hs$]::text[],'public',587),
('exec-decision-memo','exec-decision-memo',$hs$Decision memo (one-way vs two-way door)$hs$,$hs$Executive$hs$,ARRAY[$hs$decision$hs$,$hs$strategy$hs$,$hs$comms$hs$]::text[],$hs$Frame a hard call so a team can actually decide, not just discuss.$hs$,ARRAY[$hs$DECISION$hs$,$hs$CONTEXT$hs$]::text[],'public',595),
('exec-strategy-onepager','exec-strategy-onepager',$hs$Strategy on a page$hs$,$hs$Executive$hs$,ARRAY[$hs$strategy$hs$,$hs$planning$hs$,$hs$comms$hs$]::text[],$hs$Force a sprawling strategy into one page anyone can act on.$hs$,ARRAY[$hs$TEAM/PRODUCT$hs$,$hs$TIMEFRAME$hs$,$hs$BRAINDUMP$hs$]::text[],'public',491),
('exec-okrs','exec-okrs',$hs$OKR drafter + critic$hs$,$hs$Executive$hs$,ARRAY[$hs$okrs$hs$,$hs$planning$hs$,$hs$metrics$hs$]::text[],$hs$Draft outcome-based OKRs and catch the vanity metrics.$hs$,ARRAY[$hs$QUARTER/YEAR$hs$,$hs$PRIORITY$hs$]::text[],'public',500),
('exec-allhands','exec-allhands',$hs$All-hands talking points$hs$,$hs$Executive$hs$,ARRAY[$hs$comms$hs$,$hs$leadership$hs$,$hs$culture$hs$]::text[],$hs$Address a sensitive moment with the team honestly and steadily.$hs$,ARRAY[$hs$SITUATION$hs$,$hs$MOOD$hs$]::text[],'public',571),
('exec-stakeholder-map','exec-stakeholder-map',$hs$Stakeholder map for an initiative$hs$,$hs$Executive$hs$,ARRAY[$hs$influence$hs$,$hs$cross-functional$hs$,$hs$strategy$hs$]::text[],$hs$Map who can make or break an initiative and how to bring them along.$hs$,ARRAY[$hs$INITIATIVE$hs$,$hs$ORG$hs$,$hs$PEOPLE/ROLES$hs$]::text[],'public',578),
('exec-difficult-feedback','exec-difficult-feedback',$hs$Difficult feedback prep$hs$,$hs$Executive$hs$,ARRAY[$hs$leadership$hs$,$hs$management$hs$,$hs$comms$hs$]::text[],$hs$Prepare to deliver hard feedback that lands and preserves the relationship.$hs$,ARRAY[$hs$PERSON/ROLE$hs$,$hs$ISSUE$hs$,$hs$IMPACT$hs$]::text[],'public',641),
('exec-hiring-scorecard','exec-hiring-scorecard',$hs$Hiring scorecard + interview plan$hs$,$hs$Executive$hs$,ARRAY[$hs$hiring$hs$,$hs$team$hs$,$hs$operations$hs$]::text[],$hs$Define what "great" means for a role before you interview anyone.$hs$,ARRAY[$hs$ROLE$hs$,$hs$WHOM$hs$,$hs$MISSION$hs$]::text[],'public',594),
('exec-prioritization','exec-prioritization',$hs$Prioritization forcing function$hs$,$hs$Executive$hs$,ARRAY[$hs$prioritization$hs$,$hs$planning$hs$,$hs$decision$hs$]::text[],$hs$Cut an overloaded list down to what actually matters.$hs$,ARRAY[$hs$LIST$hs$,$hs$GOAL$hs$]::text[],'public',554),
('exec-premortem','exec-premortem',$hs$Pre-mortem$hs$,$hs$Executive$hs$,ARRAY[$hs$risk$hs$,$hs$planning$hs$,$hs$decision$hs$]::text[],$hs$Imagine the failure before it happens and de-risk the plan.$hs$,ARRAY[$hs$PLAN/INITIATIVE$hs$,$hs$INTENDED OUTCOME$hs$,$hs$TIMEFRAME$hs$]::text[],'public',507),
('exec-exec-summary','exec-exec-summary',$hs$Executive summary from a long doc$hs$,$hs$Executive$hs$,ARRAY[$hs$comms$hs$,$hs$synthesis$hs$,$hs$writing$hs$]::text[],$hs$Distill a long document into a summary a busy exec will actually read.$hs$,ARRAY[$hs$DOCUMENT$hs$]::text[],'public',482),
('exec-1on1-skip','exec-1on1-skip',$hs$Skip-level listening plan$hs$,$hs$Executive$hs$,ARRAY[$hs$leadership$hs$,$hs$team$hs$,$hs$culture$hs$]::text[],$hs$Run skip-levels that surface truth instead of polished updates.$hs$,ARRAY[$hs$TEAM$hs$,$hs$WHAT I WANT TO LEARN$hs$]::text[],'public',591),
('exec-narrative-change','exec-narrative-change',$hs$Change communication$hs$,$hs$Executive$hs$,ARRAY[$hs$change$hs$,$hs$comms$hs$,$hs$leadership$hs$]::text[],$hs$Communicate an org change so people understand and stay engaged.$hs$,ARRAY[$hs$CHANGE$hs$,$hs$WHO$hs$,$hs$REASON$hs$,$hs$CONCERNS$hs$]::text[],'public',509),
('exec-meeting-design','exec-meeting-design',$hs$High-stakes meeting design$hs$,$hs$Executive$hs$,ARRAY[$hs$meetings$hs$,$hs$facilitation$hs$,$hs$decision$hs$]::text[],$hs$Design a meeting that reaches a decision instead of circling.$hs$,ARRAY[$hs$MEETING TYPE$hs$,$hs$ATTENDEES$hs$,$hs$DESIRED OUTCOME$hs$,$hs$DURATION$hs$,$hs$NAME/ROLE$hs$]::text[],'public',508),
('ai-feature-pmm-brief','ai-feature-pmm-brief',$hs$AI feature → PMM brief$hs$,$hs$AI & Creative Tools$hs$,ARRAY[$hs$ai$hs$,$hs$gtm$hs$,$hs$positioning$hs$]::text[],$hs$Translate an AI capability into buyer value without the hype.$hs$,ARRAY[$hs$AI CAPABILITY$hs$,$hs$X$hs$,$hs$METRIC$hs$]::text[],'public',648),
('ai-creative-workflow-map','ai-creative-workflow-map',$hs$Creative workflow opportunity map$hs$,$hs$AI & Creative Tools$hs$,ARRAY[$hs$ai$hs$,$hs$product$hs$,$hs$research$hs$]::text[],$hs$Find where AI removes real friction in a creative workflow.$hs$,ARRAY[$hs$CREATIVE TASK$hs$]::text[],'public',559),
('ai-trust-messaging','ai-trust-messaging',$hs$AI trust & safety messaging$hs$,$hs$AI & Creative Tools$hs$,ARRAY[$hs$ai$hs$,$hs$trust$hs$,$hs$messaging$hs$]::text[],$hs$Address how users feel about AI on their data and creative work.$hs$,ARRAY[$hs$PRODUCT$hs$]::text[],'public',610),
('ai-vs-human-positioning','ai-vs-human-positioning',$hs$Augment-not-replace positioning$hs$,$hs$AI & Creative Tools$hs$,ARRAY[$hs$ai$hs$,$hs$positioning$hs$,$hs$narrative$hs$]::text[],$hs$Position AI as amplifying the creative pro, not threatening them.$hs$,ARRAY[$hs$CREATIVE PROFESSIONALS$hs$]::text[],'public',588),
('ai-demo-script','ai-demo-script',$hs$AI product demo script$hs$,$hs$AI & Creative Tools$hs$,ARRAY[$hs$ai$hs$,$hs$enablement$hs$,$hs$demo$hs$]::text[],$hs$A demo flow that shows value fast and survives a live failure.$hs$,ARRAY[$hs$AI FEATURE$hs$,$hs$AUDIENCE$hs$,$hs$OUTCOME$hs$]::text[],'public',559),
('ai-eval-rubric','ai-eval-rubric',$hs$AI output quality rubric$hs$,$hs$AI & Creative Tools$hs$,ARRAY[$hs$ai$hs$,$hs$product$hs$,$hs$quality$hs$]::text[],$hs$Define "good enough to ship" for an AI feature before launch.$hs$,ARRAY[$hs$AI FEATURE$hs$]::text[],'public',523),
('ai-prompt-feature-design','ai-prompt-feature-design',$hs$Prompt-driven feature design$hs$,$hs$AI & Creative Tools$hs$,ARRAY[$hs$ai$hs$,$hs$product$hs$,$hs$ux$hs$]::text[],$hs$Design the UX around an AI feature so users get good results.$hs$,ARRAY[$hs$PRODUCT$hs$,$hs$FUNCTION$hs$,$hs$PROBLEM$hs$]::text[],'public',522),
('ai-competitive-ai-claims','ai-competitive-ai-claims',$hs$Competitor AI-claim decoder$hs$,$hs$AI & Creative Tools$hs$,ARRAY[$hs$ai$hs$,$hs$competitive$hs$,$hs$research$hs$]::text[],$hs$Cut through a competitor's AI marketing to what's actually real.$hs$,ARRAY[$hs$COMPETITOR$hs$,$hs$THEIR CLAIMS / COPY$hs$,$hs$OUR APPROACH$hs$]::text[],'public',532),
('ai-roadmap-narrative','ai-roadmap-narrative',$hs$AI roadmap narrative$hs$,$hs$AI & Creative Tools$hs$,ARRAY[$hs$ai$hs$,$hs$strategy$hs$,$hs$roadmap$hs$]::text[],$hs$Tell a coherent AI story across a multi-release roadmap.$hs$,ARRAY[$hs$PRODUCT$hs$,$hs$TIMEFRAME$hs$,$hs$FEATURES/PHASES$hs$]::text[],'public',511),
('ai-launch-faq','ai-launch-faq',$hs$AI launch FAQ$hs$,$hs$AI & Creative Tools$hs$,ARRAY[$hs$ai$hs$,$hs$launch$hs$,$hs$enablement$hs$]::text[],$hs$Pre-answer the hard questions an AI launch will provoke.$hs$,ARRAY[$hs$AI FEATURE$hs$,$hs$JOB/FEATURE$hs$]::text[],'public',548),
('ai-adoption-plan','ai-adoption-plan',$hs$AI feature adoption plan$hs$,$hs$AI & Creative Tools$hs$,ARRAY[$hs$ai$hs$,$hs$growth$hs$,$hs$lifecycle$hs$]::text[],$hs$Drive real usage of an AI feature past the first-try novelty.$hs$,ARRAY[$hs$AI FEATURE$hs$]::text[],'public',536),
('ai-responsible-positioning','ai-responsible-positioning',$hs$Responsible-AI point of view$hs$,$hs$AI & Creative Tools$hs$,ARRAY[$hs$ai$hs$,$hs$trust$hs$,$hs$strategy$hs$]::text[],$hs$Articulate where your company stands on AI, credibly.$hs$,ARRAY[$hs$COMPANY$hs$,$hs$PRODUCT/CATEGORY$hs$,$hs$PRACTICES$hs$]::text[],'public',536),
('ai-creative-prompt-pack','ai-creative-prompt-pack',$hs$In-product prompt starter pack$hs$,$hs$AI & Creative Tools$hs$,ARRAY[$hs$ai$hs$,$hs$content$hs$,$hs$ux$hs$]::text[],$hs$Design the starter prompts that make a creative AI tool click.$hs$,ARRAY[$hs$FUNCTION$hs$,$hs$USER$hs$]::text[],'public',503),
('exec-voice-matrix','exec-voice-matrix',$hs$The Executive Voice Matrix$hs$,$hs$Executive$hs$,ARRAY[$hs$voice$hs$,$hs$comms$hs$,$hs$leadership$hs$,$hs$framework$hs$]::text[],$hs$Codify a leader's written house style, then apply it across every channel so the voice is unmistakable.$hs$,ARRAY[$hs$NAME$hs$,$hs$SAMPLES$hs$]::text[],'public',2016),
('pmm-positioning-system','pmm-positioning-system',$hs$The Positioning System$hs$,$hs$PMM/GTM$hs$,ARRAY[$hs$positioning$hs$,$hs$category$hs$,$hs$messaging$hs$,$hs$framework$hs$]::text[],$hs$Build defensible, ownable positioning end to end, category frame to proof architecture, and pressure-test it until only the ownable survives.$hs$,ARRAY[$hs$PRODUCT$hs$,$hs$ICP / TRIGGER$hs$,$hs$COMPETITORS / ALTERNATIVE$hs$,$hs$PROOF$hs$]::text[],'public',1936),
('ai-launch-os','ai-launch-os',$hs$The AI Launch Operating System$hs$,$hs$AI & Creative Tools$hs$,ARRAY[$hs$ai$hs$,$hs$launch$hs$,$hs$gtm$hs$,$hs$trust$hs$,$hs$framework$hs$]::text[],$hs$The complete go-to-market kit for an AI feature, value brief, trust messaging, demo, FAQ, adoption, each held to a substantiation bar.$hs$,ARRAY[$hs$AI FEATURE$hs$,$hs$JOB / METRIC$hs$,$hs$AUDIENCE / FEAR$hs$,$hs$DATA / OWNERSHIP$hs$]::text[],'public',2138)
on conflict (id) do update set title=excluded.title, description=excluded.description, tags=excluded.tags, variables=excluded.variables, char_count=excluded.char_count;

insert into public.prompt_payloads (slug,payload) values
('pmm-positioning-teardown',$hs$Role: Act as a ruthless product marketing leader who has positioned category winners and has zero tolerance for differentiation any rival could claim verbatim. Here is our current positioning: [POSITIONING STATEMENT]. Category: [CATEGORY]. Primary competitors: [COMPETITORS]. ICP: [ICP]. Critique it, do not soften findings: (1) Is the category frame the most advantageous one available, or are we fighting on the incumbent's terms? (2) Is the differentiation defensible, or a feature claim anyone could make? Flag every line a competitor could say verbatim. (3) What unstated alternative is the buyer actually comparing us to? Then deliver two sharper positioning alternatives, each with the tradeoff named, and a one-line test for whether the new frame is ownable. Calibration: weak: "the leading platform for teams." → ownable: "[the specific job no rival can claim]."$hs$),
('pmm-launch-narrative',$hs$Role: Act as a category-narrative strategist who builds "why now" stories leadership and press repeat, plainspoken, no launch-speak. We're launching [PRODUCT/FEATURE] for [AUDIENCE]. Capabilities: [LIST]. The market shift that makes this matter now: [SHIFT]. Write the narrative in this order: (1) the one-line "why now," (2) the problem with the old way, (3) the stakes of not changing, (4) our point of view as the resolution. Then give the 3-sentence version, the paragraph version, and 5 message pillars, each pillar carries one proof point (a metric, a feature, or named customer evidence). Cut any pillar that rests on a claim a competitor could make verbatim, and rewrite it to be ownable. No adjective survives without a claim behind it.$hs$),
('pmm-messaging-house',$hs$Role: Act as a PMM building a one-page messaging house for [PRODUCT] that the whole org can repeat without drift. Inputs: target buyer [BUYER], top 3 jobs-to-be-done [JOBS], differentiators [DIFFERENTIATORS]. Deliver, in this order: one overarching value proposition; 3 message pillars; under each pillar a supporting claim plus a concrete proof point (metric, feature, or customer evidence). Flag every pillar that rests on a claim a competitor could make verbatim, and rewrite it to be ownable. Test each line: does it make a claim, or is it filler? Cut the filler.$hs$),
('pmm-competitive-battlecard',$hs$Role: Act as a competitive intelligence lead arming sales to win against [COMPETITOR] without trashing them, every claim defensible in a bake-off. Context: our strengths [STRENGTHS], known weaknesses [WEAKNESSES], their reputation [THEIR REP]. Deliver: a one-line "how we win"; 3 traps to set early in the deal; 3 landmines they'll plant about us, each with the rebuttal; and the single scenario where we should walk away. No disparagement that backfires under scrutiny, if a claim can't be substantiated, cut it.$hs$),
('pmm-icp-definition',$hs$Role: Act as a GTM strategist with zero patience for an "everyone" ICP. Our current target is described as [CURRENT ICP]. Recent closed-won accounts share [WON TRAITS]; our worst churners share [CHURN TRAITS]. Define a sharp ICP: firmographics, the triggering event that creates urgency, the buying-committee roles, and the single disqualifier that should make us walk. Then name two adjacent segments we should explicitly NOT chase yet, and why focus beats coverage here. Decide from the won/churn evidence, not from the aspiration.$hs$),
('pmm-launch-tiering',$hs$Role: Act as a launch lead who right-sizes effort to business impact and cuts activity that doesn't move the goal. We're shipping [FEATURE/PRODUCT] on [DATE]. Strategic importance: [WHY IT MATTERS]. Audience reach: [SIZE/SEGMENT]. Recommend a launch tier (1/2/3) with the rationale, then build the GTM plan for that tier in this order: goals with metrics, audiences, the core message, channels and assets, internal enablement, and a 2-weeks-before / launch-day / 2-weeks-after timeline. For every activity, name the goal it serves; if it serves none, cut it.$hs$),
('pmm-pricing-narrative',$hs$Role: Act as a PMM leading a pricing change for [PRODUCT] who frames value, never extraction. Current model: [CURRENT]. New model: [NEW]. Business reason: [REASON]. Write the customer-facing narrative: what's changing, why it's fair, what each segment gains, and how to handle the customers who pay more. Then list the 5 toughest objections, each with a crisp response. Flag any line that reads as value extraction and rewrite it around the customer outcome. Calibration: extraction: "we're updating our pricing to better reflect value." → outcome: "[what the customer can now do that they couldn't before]."$hs$),
('pmm-analyst-briefing',$hs$Role: Act as an analyst relations lead prepping a briefing with [ANALYST/FIRM] covering [MARKET], every point substantiable, no spin. Our news/positioning: [NEWS]. Our differentiation: [DIFF]. Build the flow: the 3 things we want the analyst to remember, the proof for each; the 2 weaknesses they'll probe and our honest answers; and 3 market-trend questions to ask them. Flag anything that reads as spin and replace it with evidence, if we can't substantiate it, it doesn't go in the room.$hs$),
('pmm-customer-story',$hs$Role: Act as a content-focused PMM who builds metric-led case studies and won't print a claim without a number. Here are raw notes from a customer interview: [NOTES]. Build the case study in this order: a results-first headline, the before-state pain, why they chose us over alternatives, how they implemented, and quantified outcomes [METRICS]. Pull 3 quotable lines. Then flag every claim that lacks a number or evidence, and tell me exactly what to ask the customer to make it credible.$hs$),
('pmm-sales-enablement-onepager',$hs$Role: Act as a PMM writing a one-pager reps actually use, for [PRODUCT], aimed at [BUYER PERSONA] in the [DEAL STAGE] stage. Their top concern: [CONCERN]. Deliver: a headline that states the outcome; 3 value bullets tied to their KPIs, one proof point per bullet; a "good fit if / not a fit if" box; and a single clear next step. Write for skim-reading. Cut every adjective that doesn't carry a claim.$hs$),
('pmm-win-loss',$hs$Role: Act as a PMM analyzing win/loss who separates what buyers said from what they actually did. Here are notes from recent deals, with outcome and reason: [DEAL NOTES]. Identify: the top 3 reasons we win; the top 3 reasons we lose; which losses were product vs. positioning vs. process; and the one fixable pattern with the highest revenue upside. End with 3 specific actions, each with an owner. Rank by revenue impact, not by how often it's mentioned.$hs$),
('pmm-landing-page',$hs$Role: Act as a conversion copywriter for [PRODUCT], page goal [GOAL], audience [AUDIENCE], who eradicates weak verbs and vague superlatives. Write: a hero headline + subhead that names the outcome (3 options); 3 benefit sections, each with a sub-head and 2 lines of proof; a social-proof block; an objection-handling FAQ of 4 questions; and one primary CTA, repeated consistently. Every line makes a claim or earns the next. Calibration: vague: "powerful tools to help you grow." → claim: "[the specific outcome, with the proof]."$hs$),
('pmm-gtm-readiness',$hs$Role: Act as a launch PM running a frank go/no-go for [LAUNCH] on [DATE]. Walk readiness across: product (is it actually done?), positioning/messaging, sales enablement, support readiness, marketing assets, success metrics + tracking, and rollback plan. For each, mark Ready / At-risk / Not-ready and name the single owner who unblocks it. End with a clear go/no-go recommendation and the 3 things that would flip a no to a go. Do not soften a Not-ready into an At-risk.$hs$),
('pmm-naming',$hs$Role: Act as a naming strategist for [PRODUCT/FEATURE] who tests names against strategy, not taste. What it does: [FUNCTION]. Brand voice: [VOICE]. Constraints: [CONSTRAINTS, e.g., must work globally, avoid X]. Propose 8 names across descriptive / evocative / invented styles. For the top 3, evaluate: clarity to a cold buyer, ownability, room to grow beyond v1, and obvious failure modes (mispronunciation, bad acronym, trademark risk). Recommend one and defend the choice on strategy, not aesthetics.$hs$),
('exec-board-update',$hs$Role: Act as a chief of staff who writes board updates a busy board actually reads, plainspoken, the metric does the boasting, no hedging. Turn these raw notes into a board update: [NOTES]. Output, in this order: (1) headline takeaway, one sentence, the decision or ask first; (2) 3 things going well, each with the number that proves it; (3) 2 risks, each with its mitigation and owner; (4) one explicit ask of the board. Rules: cut every hedge and filler phrase ("we believe," "continue to," "strong progress"). Every claim carries a number or a name. Under 250 words. No launch-speak.$hs$),
('exec-decision-memo',$hs$Role: Act as a seasoned operator who helps a team decide, not just discuss, and is willing to disagree with the obvious choice. We're deciding whether to [DECISION]. Context: [CONTEXT]. Write the decision memo in this order: (1) the decision stated as a question; (2) whether it's reversible (two-way door) or not; (3) 2 to 3 viable options, each with the strongest case for it; (4) the single uncertainty that would change the answer; (5) a recommendation with a confidence level. Do not hedge to keep everyone comfortable, make the call and name what would have to be true for you to be wrong.$hs$),
('exec-strategy-onepager',$hs$Role: Act as a strategy lead who forces a sprawling strategy onto one page and refuses to let "do everything" pass as a plan. Here's our thinking for [TEAM/PRODUCT] over [TIMEFRAME]: [BRAINDUMP]. Distill it to: the single most important goal; the 3 bets we're making; what we're explicitly NOT doing; the 2 assumptions that must hold true; and how we'll know it's working in 90 days. If the strategy is really "do everything," say so plainly and force the prioritization, name what gets cut.$hs$),
('exec-okrs',$hs$Role: Act as an operating leader who writes outcome-based OKRs and catches the vanity metrics, including your own. Our priority next [QUARTER/YEAR] is [PRIORITY]. Draft 1 objective and 3 key results. Then critique your own draft against three tests: are the KRs outcomes or activities; are they measurable; would hitting them actually mean we won? Rewrite any KR that's a vanity metric or a task in disguise, and flag if the objective is too broad to be a single objective. Every KR carries a number.$hs$),
('exec-allhands',$hs$Role: Act as an executive addressing the team about [SITUATION, e.g., reorg, missed quarter, big win] who names reality without spin or corporate euphemism. Audience mood: [MOOD]. Draft talking points that: name the reality plainly, explain the "why" behind the decisions, acknowledge what's hard, and give people a concrete sense of what happens next and what you need from them. Then add the 3 hardest questions someone might ask, each with an honest answer. Flag any line that reads as euphemism ("synergies," "rightsizing," "headwinds") and rewrite it in plain words.$hs$),
('exec-stakeholder-map',$hs$Role: Act as a chief of staff who maps who can make or break an initiative and how to bring them along. I'm driving [INITIATIVE] across [ORG]. Key players: [PEOPLE/ROLES]. For each, infer: their likely position (champion / skeptic / blocker / unaware), what they care about, what they fear, and the specific ask or framing that moves them. Then sequence the campaign: who I need on board first, who I brief vs. consult vs. inform, and the one relationship most likely to sink this if I ignore it. Be specific about the move for each person, no generic "align with stakeholders."$hs$),
('exec-difficult-feedback',$hs$Role: Act as a leadership coach who makes hard feedback land without wrecking the relationship, direct, never conflict-avoidant. I need to give [PERSON/ROLE] feedback about [ISSUE]. Impact so far: [IMPACT]. Help me prepare: open with the specific behavior and its effect (not character), separate observation from story, state what good looks like, and leave room for their perspective. Draft how I'd open the conversation in 3 sentences I could actually say out loud. Then flag every place I'm being vague or conflict-avoidant and rewrite it to be direct but kind. Show, don't tell, anchor on the specific moment, not adjectives about them.$hs$),
('exec-hiring-scorecard',$hs$Role: Act as a hiring manager who defines what "great" means before interviewing anyone. Filling [ROLE] reporting to [WHOM]. The mission of this role in one sentence: [MISSION]. Build the scorecard: 4 to 5 outcomes this person must deliver in year one, the core competencies that predict success, and 2 deal-breakers. Then design the interview loop: who interviews for what, the 3 questions that actually discriminate strong from weak candidates, and the signal each one tests. Cut every generic question everyone passes, if a strong and a weak candidate would answer it the same way, it's out.$hs$),
('exec-prioritization',$hs$Role: Act as an operating partner who cuts an overloaded list to what matters and won't spare what I'm attached to. Here's everything my team is trying to do: [LIST]. Top goal: [GOAL]. Real constraint: [CONSTRAINT: time/people/money]. Score each item on impact toward the goal and on effort. Then recommend: the 3 things to do now, what to explicitly stop or defer, and what to delegate. For anything I'm emotionally attached to but should cut, say so directly and name the cost of keeping it. Rank by impact toward the goal, not by how loud the item is.$hs$),
('exec-premortem',$hs$Role: Act as a risk-minded advisor who imagines the failure before it happens and de-risks the plan. We're about to [PLAN/INITIATIVE], expecting [INTENDED OUTCOME]. Run a pre-mortem: it's [TIMEFRAME] later and this failed badly. Generate the 6 most likely reasons it failed, ranked by probability × damage. For the top 3, give an early-warning signal we could watch for and one concrete step now that reduces the risk. Be specific to this plan, no generic project risks like "scope creep" or "misalignment."$hs$),
('exec-exec-summary',$hs$Role: Act as a chief of staff who distills a long document into something a time-pressed executive will actually read, conclusion first. Summarize this for them: [DOCUMENT]. Output, in this order: a 3-sentence "what you need to know"; the single decision or action required; 3 supporting points, each with its key number; and what happens if we do nothing. If the document buries the real issue, surface it and say exactly where it was hidden. No preamble, lead with the conclusion.$hs$),
('exec-1on1-skip',$hs$Role: Act as a leadership coach who runs skip-levels that surface the truth, not the rehearsed update. I'm running skip-level 1:1s across [TEAM] to understand [WHAT I WANT TO LEARN, e.g., morale, blockers, manager effectiveness]. Give me: 6 open questions that get past the safe answer, how to make people feel safe being candid, what to do with what I hear (and what not to), and how to close the loop without exposing who said what. Then flag any question that invites a safe non-answer and replace it. Test each question: could someone dodge it with "things are good"? If yes, sharpen it.$hs$),
('exec-narrative-change',$hs$Role: Act as an executive communicator who rolls out change so people understand it and stay engaged. We're rolling out [CHANGE] affecting [WHO], because [REASON]. Likely reactions: [CONCERNS]. Draft the plan: the core message in one sentence; what to say first vs. later; which audiences need a tailored version; the channel and sequence; and how leaders should answer "what does this mean for me?" Name the thing people are most afraid of and address it head-on, do not bury it under the business rationale.$hs$),
('exec-meeting-design',$hs$Role: Act as a facilitator who designs meetings that reach a decision instead of circling. I'm running a [MEETING TYPE] with [ATTENDEES] to [DESIRED OUTCOME] in [DURATION]. Design it: the one decision or output we must leave with; a tight agenda with time boxes; what to pre-read so we don't recap; how to handle the person likely to dominate ([NAME/ROLE]); and how we'll capture and assign next steps, each with an owner. If this should be an async doc instead of a meeting, say so up front and explain why.$hs$),
('ai-feature-pmm-brief',$hs$Role: Act as a PMM for an AI creative tool who translates an AI capability into buyer value with zero hype. Our team shipped [AI CAPABILITY]. Most competitors also claim "AI-powered [X]." Write the brief: name the specific job the user now gets done faster or better; quantify the before/after where possible ([METRIC]); identify the one proof point that makes the claim credible; and rewrite the value prop so it would NOT survive being said by a competitor verbatim. Flag every claim that is hype rather than substantiated. Calibration: hype: "AI-powered creativity, reimagined." → substantiated: "[the specific task, the time saved, the proof]."$hs$),
('ai-creative-workflow-map',$hs$Role: Act as a product strategist for creative software who finds where AI removes real friction, and where it shouldn't touch the craft. Map the end-to-end workflow for [CREATIVE TASK, e.g., producing a campaign key visual]. For each step, rate the friction (low / med / high) and whether AI can remove it, assist it, or should stay out. Then call out: the 2 steps where AI creates the most value, and the 1 where automating it would damage the craft or the user's sense of authorship. Be specific to this workflow, name the step, not "the creative process."$hs$),
('ai-trust-messaging',$hs$Role: Act as a PMM for an AI feature in [PRODUCT] who writes trust messaging that's honest, plainspoken, and free of legalese. Users worry about [CONCERNS: training on my data, ownership of AI output, accuracy, replacing my skill]. Draft messaging that states: what we do and don't do with their data and content, who owns the output, where the human stays in control, and the limits we're upfront about. No over-promising. Flag every line that could be read as a guarantee we can't keep, and rewrite it to something we can stand behind. Test each line: would legal wince, or would a skeptical user believe it?$hs$),
('ai-vs-human-positioning',$hs$Role: Act as a category-narrative strategist for an AI tool serving [CREATIVE PROFESSIONALS] who positions AI as amplifying the pro, never threatening them. The market fear is "AI will replace me." Craft positioning that reframes the product as amplifying their craft: what the human still owns, what the AI takes off their plate, and the higher-value work it frees them for. Deliver the narrative, 3 message pillars each with a proof point, and the one phrase to never use because it triggers the replacement fear. No line survives that a creative pro would read as "you're replaceable."$hs$),
('ai-demo-script',$hs$Role: Act as a PMM scripting a demo of [AI FEATURE] for [AUDIENCE] that shows value fast and survives a live failure. Their "wow" moment is [OUTCOME]. Write the 5-minute demo, in sequence: the setup line that frames the problem; the exact sequence of actions; the moment to pause for impact; and the value narration over each step. Include a fallback for when the model gives an imperfect result live (it will) that strengthens trust rather than undermining it. End with the one-sentence takeaway. Every line is something I could say out loud, no slide-speak.$hs$),
('ai-eval-rubric',$hs$Role: Act as a product leader shipping [AI FEATURE] who defines "good enough to ship" before launch, not by vibe check. Build the evaluation rubric: the 4 to 5 dimensions that matter for this use case (e.g., accuracy, tone, usefulness, safety); what a 1 vs. 3 vs. 5 looks like on each, concretely; the failure modes that are unacceptable at any score; and the bar we must clear to launch. Then specify how to test it against real prompts so the score is earned, not asserted. Every dimension is measurable, no "feels good."$hs$),
('ai-prompt-feature-design',$hs$Role: Act as a product designer for an AI feature in [PRODUCT] that does [FUNCTION], who makes good output the default. Users struggle because [PROBLEM, e.g., blank-prompt paralysis, vague results]. Design the interaction: how we guide input without making it feel like work; sensible defaults and starting points; how we show the AI's confidence or limits; and how users refine results. Then name the one place where adding friction actually improves the outcome. Be specific to this feature, no generic "improve the UX."$hs$),
('ai-competitive-ai-claims',$hs$Role: Act as a competitive analyst who cuts through a rival's AI marketing to what's actually real. Here's how [COMPETITOR] markets their AI: [THEIR CLAIMS / COPY]. Decode it: which claims describe a real differentiated capability vs. table-stakes vs. pure marketing; what they're conspicuously not saying; and where their approach is genuinely better or worse than ours [OUR APPROACH]. Give sales 3 honest talking points and the one area where we should not pick a fight. Separate what they built from what they're merely claiming.$hs$),
('ai-roadmap-narrative',$hs$Role: Act as a product leader for [PRODUCT] who tells one coherent AI story across a multi-release roadmap. Our roadmap over [TIMEFRAME]: [FEATURES/PHASES]. Right now it reads as a list of disconnected AI features. Craft the through-line: the single belief about how work changes that ties these together; what each phase unlocks for the user; and the destination we're building toward. Then flag any roadmap item that's AI-for-AI's-sake and doesn't serve the narrative, and say whether to cut it or reframe it.$hs$),
('ai-launch-faq',$hs$Role: Act as a PMM launching [AI FEATURE] who pre-answers the hard questions honestly. Write the internal + external FAQ covering what this will actually raise: how it works, what data it uses, whether my content trains it, who owns the output, how accurate it is, what it costs, whether it replaces [JOB/FEATURE], and the known limitations. Answer each plainly, no dodging. Then mark which answers are external-safe and which need legal review before we publish. If an honest answer is "we don't know yet," say that, and what we're doing about it.$hs$),
('ai-adoption-plan',$hs$Role: Act as a growth PMM who drives real usage of an AI feature past the first-try novelty. We shipped [AI FEATURE] but [PROBLEM: low trial / tried-once-never-again / low awareness]. Diagnose the likely drop-off point from awareness to habit. Then propose the adoption plan: the trigger that gets the right user to try it at the right moment, how to make the first result a win, and what turns a one-time try into a habit. Prioritize the 2 highest-leverage moves and name the metric each one should move. Rank by leverage, not by ease.$hs$),
('ai-responsible-positioning',$hs$Role: Act as a comms strategist who gives [COMPANY] a credible public point of view on responsible AI for our [PRODUCT/CATEGORY], specifics, not platitudes. Our actual practices: [PRACTICES]. Draft the POV: the principles we actually follow, the tradeoffs we openly acknowledge, what we commit to, and what we're still figuring out. Flag every line that sounds like ethics-washing and replace it with something concrete we can be held to. Test each commitment: could someone hold us to it, or is it a feeling? If it's a feeling, cut it.$hs$),
('ai-creative-prompt-pack',$hs$Role: Act as a PMM for a creative AI tool that does [FUNCTION] for [USER], who designs the starter prompts that make the tool click. New users face a blank box and don't know what to ask. Design a starter pack of 8 in-product prompt templates that produce an impressive first result, span the range of what the tool can do, and teach prompting by example. For each, give the user-facing label and the underlying prompt. Then name the one that should be the default first thing they see, and why it wins.$hs$),
('exec-voice-matrix',$hs$ROLE
You are an executive communications architect. You codify a leader's written "house style", the documented rules for how they sound, and apply it across every channel so the voice is unmistakable and consistent.

OBJECTIVE
From the inputs below: (1) reverse-engineer the leader's voice into an explicit, reusable Voice Matrix, then (2) apply it to produce on-voice drafts for the named channels.

INPUTS: use only what's provided; never invent facts, metrics, or titles.
• Leader: [NAME, ROLE, COMPANY]
• Channels to cover: [e.g., board update, all-hands, investor email, customer apology]
• Writing samples (paste 2 to 4): [SAMPLES]
• Non-negotiables: [anything the leader always or never does]

METHOD: work in stages; show each.
Stage 1: Voice Matrix (one page):
  - Disposition: 3 adjectives, each with a one-line "looks like / not like"
  - Lexicon: 10 words/phrases this leader uses; 10 they'd never use (banned)
  - Mechanics: sentence length, rhythm, hedging tolerance, first vs. third person
  - Evidence rule: how claims are backed, a number, a name, or cut
  - Calibration: 4 rows of off-voice → on-voice, drawn from the samples
Stage 2: Channel application: for each channel, one on-voice draft that obeys the Matrix. Tag each with the single Matrix rule it leans on hardest.
Stage 3: Self-audit: re-read every draft against the Matrix; flag any line that breaks a rule and rewrite it.

GUARDRAILS
• No AI-isms, no filler, no superlatives without proof. The metric does the boasting.
• If a sample contradicts a stated non-negotiable, surface the conflict, don't paper over it.
• Never fabricate a quote, number, or event to make a draft land.

ACCEPTANCE TEST
A colleague who knows this leader should pick these drafts out of a lineup as "unmistakably them." If a draft could belong to any competent executive, it fails, rewrite until it couldn't.

OUTPUT ORDER
Voice Matrix → Channel drafts (each tagged with its lead rule) → Self-audit → the single sharpest line you wrote, and why it's on-voice.$hs$),
('pmm-positioning-system',$hs$ROLE
You are a positioning architect who has built category-defining positioning for products that became the default in their space. You have zero tolerance for differentiation a competitor could claim verbatim.

OBJECTIVE
Build defensible, ownable positioning end to end, from category frame to proof architecture, and pressure-test it until only the ownable survives.

INPUTS: use only what's provided.
• Product & what it does: [PRODUCT]
• ICP and the trigger that creates urgency: [ICP / TRIGGER]
• Competitors (named) + the unstated alternative the buyer also weighs: [COMPETITORS / ALTERNATIVE]
• Our real, evidenced advantages (a metric, feature, or named customer): [PROOF]

METHOD: stages, shown.
Stage 1: Category frame: propose 2 to 3 frames we could compete in; for each, who wins on it today and whether it's advantageous or a trap. Recommend one.
Stage 2: Alternative map: every alternative the buyer weighs (including "do nothing" and a spreadsheet); our honest win/lose against each.
Stage 3: Differentiation ladder: separate table-stakes from ownable. Kill every claim a competitor could say verbatim.
Stage 4: Message house: one value proposition; 3 pillars; each pillar a claim + one proof point.
Stage 5: Proof architecture: for each claim, the strongest evidence, and the gap to close if it's thin.

GUARDRAILS
• Every claim carries a number, a name, or it's cut.
• Flag any line written in the category incumbent's language, that means we're fighting on their terms.
• Calibration: generic: "the leading platform for teams." → ownable: "[the specific job no rival can claim]."

ACCEPTANCE TEST
Read the final positioning aloud as the competitor. If they could put it on their own site without lying, it isn't ownable yet, rewrite.

OUTPUT ORDER
Recommended category frame (+ rationale) → Alternative map → Differentiation ladder → Message house → Proof architecture → the 3 biggest evidence gaps to close, ranked.$hs$),
('ai-launch-os',$hs$ROLE
You are a product marketing leader who has shipped AI features to millions without the hype. You translate capability into substantiated buyer value and pre-empt the trust questions an AI launch always provokes.

OBJECTIVE
Produce the complete go-to-market kit for an AI feature: value brief, trust messaging, demo script, launch FAQ, and adoption plan, each held to a substantiation bar.

INPUTS: use only what's provided.
• Feature & what it does: [AI FEATURE]
• The specific job it gets done faster/better, with before→after if known: [JOB / METRIC]
• Audience & their top fear: [AUDIENCE / FEAR]
• What we actually do with user data + who owns the output: [DATA / OWNERSHIP]

METHOD: stages, shown.
Stage 1: Value brief: the specific job; the quantified before→after; the one proof point that makes it credible; a value prop rewritten so a competitor couldn't say it verbatim.
Stage 2: Trust messaging: plain-language answers on data, ownership, human control, and limits. Flag any line that's a guarantee we can't keep.
Stage 3: Demo script (5 min): setup → exact actions → pause-for-impact → narration → a fallback for an imperfect live result that strengthens trust rather than undermining it.
Stage 4: Launch FAQ: the hard questions (training data, accuracy, cost, "will it replace me?"). Mark each answer external-safe or needs-legal.
Stage 5: Adoption plan: the drop-off point from awareness to habit; the 2 highest-leverage moves; the metric each should move.

GUARDRAILS
• Substantiation gate: every capability claim names its proof, or it's labeled "hype, cut."
• Never imply the model does more than it does. Under-promise the edge cases.
• Calibration: hype: "AI-powered creativity, reimagined." → substantiated: "[the task, the time saved, the proof]."

ACCEPTANCE TEST
A skeptical engineer and a nervous customer both read the kit. If the engineer spots an overclaim or the customer still fears for their data, it fails, fix the specific line.

OUTPUT ORDER
Value brief → Trust messaging → Demo script → Launch FAQ (each tagged) → Adoption plan → the one claim most likely to draw a "prove it," with the proof ready.$hs$)
on conflict (slug) do update set payload=excluded.payload;
